# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_TRUSTONIC_TEE_SUPPORT) += gud/
obj-$(CONFIG_TEEGRIS_TEE_SUPPORT) += tzdev/
obj-$(CONFIG_SAMSUNG_TUI) += tui/
obj-$(CONFIG_MICROTRUST_TEE_SUPPORT) += teei/
