/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#ifndef __MTK_DISP_OVL_OUTPUTPROC_REG_H__
#define __MTK_DISP_OVL_OUTPUTPROC_REG_H__

#include "../mtk_drm_ddp_comp.h"

enum SDPA_USAGE_COMP {
	CRTC_0_1ST_EXDMA_W_RPO = 0,
	CRTC_0_1ST_EXDMA_WO_RPO,
	CRTC_0_SYS1_1ST_EXDMA_W_RPO,
	CRTC_0_SYS1_1ST_EXDMA_WO_RPO,
	CRTC_1_1ST_EXDMA,
	CRTC_2_1ST_EXDMA,
	CRTC_3_1ST_EXDMA,
	SYS_LAST_EXDMA,
	EXDMA_SYS_GAP_W_RPO,
	EXDMA_SYS_GAP_WO_RPO,
	RPO_0_EXDMA,
	RPO_1_EXDMA,
	MML_EXDMA,
	CRTC_0_1ST_BLENDER,
	CRTC_0_SYS1_1ST_BLENDER,
	CRTC_1_1ST_BLENDER,
	CRTC_2_1ST_BLENDER,
	CRTC_3_1ST_BLENDER,
	SYS_LAST_BLENDER,
	BLENDER_SYS_GAP,
	USAGE_COMP_TOTAL,
};

static const unsigned int ovl_spda_mapping_mt6991[USAGE_COMP_TOTAL] = {
	[CRTC_0_1ST_EXDMA_W_RPO] = DDP_COMPONENT_OVL_EXDMA3,
	[CRTC_0_1ST_EXDMA_WO_RPO] = DDP_COMPONENT_OVL_EXDMA2,
	[CRTC_1_1ST_EXDMA] = DDP_COMPONENT_OVL1_EXDMA6,
	[CRTC_2_1ST_EXDMA] = DDP_COMPONENT_OVL1_EXDMA6,
	[CRTC_3_1ST_EXDMA] = DDP_COMPONENT_OVL1_EXDMA4,
	[SYS_LAST_EXDMA] = DDP_COMPONENT_OVL_EXDMA9,
	[EXDMA_SYS_GAP_W_RPO] = 3,
	[EXDMA_SYS_GAP_WO_RPO] = 2,
	[RPO_0_EXDMA] = DDP_COMPONENT_OVL_EXDMA2,
	[RPO_1_EXDMA] = DDP_COMPONENT_OVL1_EXDMA2,
	[MML_EXDMA] = DDP_COMPONENT_OVL_EXDMA0,
	[CRTC_0_1ST_BLENDER] = DDP_COMPONENT_OVL0_BLENDER1,
	[CRTC_0_SYS1_1ST_BLENDER] = DDP_COMPONENT_OVL1_BLENDER0,
	[CRTC_1_1ST_BLENDER] = DDP_COMPONENT_OVL1_BLENDER5,
	[CRTC_2_1ST_BLENDER] = DDP_COMPONENT_OVL1_BLENDER5,
	[CRTC_3_1ST_BLENDER] = DDP_COMPONENT_OVL1_BLENDER7,
	[SYS_LAST_BLENDER] = DDP_COMPONENT_OVL0_BLENDER9,
	[BLENDER_SYS_GAP] = 0,
};

static const unsigned int ovl_spda_mapping_mt6993[USAGE_COMP_TOTAL] = {
	[CRTC_0_1ST_EXDMA_W_RPO] = DDP_COMPONENT_OVL_EXDMA3,
	[CRTC_0_1ST_EXDMA_WO_RPO] = DDP_COMPONENT_OVL_EXDMA2,
	[CRTC_0_SYS1_1ST_EXDMA_W_RPO] = DDP_COMPONENT_OVL1_EXDMA3,
	[CRTC_0_SYS1_1ST_EXDMA_WO_RPO] = DDP_COMPONENT_OVL1_EXDMA2,
	[CRTC_1_1ST_EXDMA] = DDP_COMPONENT_OVL2_EXDMA2,
	[CRTC_2_1ST_EXDMA] = 0,
	[CRTC_3_1ST_EXDMA] = 0,
	[SYS_LAST_EXDMA] = DDP_COMPONENT_OVL_EXDMA7,
	[EXDMA_SYS_GAP_W_RPO] = 5, // DDP_COMPONENT_OVL1_EXDMA3 - DDP_COMPONENT_OVL_EXDMA8
	[EXDMA_SYS_GAP_WO_RPO] = 4, // DDP_COMPONENT_OVL1_EXDMA2 - DDP_COMPONENT_OVL_EXDMA8
	[RPO_0_EXDMA] = DDP_COMPONENT_OVL_EXDMA2,
	[RPO_1_EXDMA] = DDP_COMPONENT_OVL1_EXDMA2,
	[MML_EXDMA] = DDP_COMPONENT_OVL_EXDMA0,
	[CRTC_0_1ST_BLENDER] = DDP_COMPONENT_OVL0_BLENDER1,
	[CRTC_0_SYS1_1ST_BLENDER] = DDP_COMPONENT_OVL1_BLENDER0,
	[CRTC_1_1ST_BLENDER] = DDP_COMPONENT_OVL2_BLENDER0,
	[CRTC_2_1ST_BLENDER] = 0,
	[CRTC_3_1ST_BLENDER] = 0,
	[SYS_LAST_BLENDER] = DDP_COMPONENT_OVL0_BLENDER7,
	[BLENDER_SYS_GAP] = 2, // DDP_COMPONENT_OVL1_BLENDER0 - DDP_COMPONENT_OVL0_BLENDER8
};

#endif
